import { Injectable } from '@angular/core';

export interface ToolCatalogItem {
  id: string;
  name: string;
  description: string;
  category: string;
  route: string;
  tags: string[];
  icon?: string;
  featured?: boolean;
}

@Injectable({
  providedIn: 'root',
})
export class ToolCatalog {
  private readonly tools: ToolCatalogItem[] = [
    {
      id: 'codice-fiscale',
      name: 'Codice Fiscale',
      description: 'Generate Italian tax code from personal details.',
      category: 'Finance',
      route: '/calcola-codice-fiscale',
      tags: ['italy', 'tax', 'fiscal', 'code'],
      icon: 'badge',
      featured: true,
    },
    {
      id: 'codice-fiscale-inverso',
      name: 'Codice Fiscale Inverso',
      description: 'Decode an Italian fiscal code — extract birth date, gender and municipality.',
      category: 'Finance',
      route: '/codice-fiscale-inverso',
      tags: ['italy', 'tax', 'fiscal', 'decode', 'reverse'],
      icon: 'manage_search',
    },
    {
      id: 'base64',
      name: 'Base64 / UnBase64',
      description: 'Encode and decode plain text safely using Base64.',
      category: 'Developer Tools',
      route: '/base64',
      tags: ['encoding', 'decoder', 'text', 'binary'],
      icon: 'code',
      featured: true,
    },
    {
      id: 'iban-checker',
      name: 'IBAN Checker',
      description: 'Validate IBAN control digits (mod-97). Format check only — no bank lookup.',
      category: 'Finance',
      route: '/tools/iban-checker',
      tags: ['iban', 'bank', 'validation', 'mod97', 'finance'],
      icon: 'account_balance',
    },
    {
      id: 'cf-checker',
      name: 'Codice Fiscale Checker',
      description: 'Validate the control character of an Italian fiscal code via generic regex + checksum.',
      category: 'Finance',
      route: '/tools/verifica-validita-codice-fiscale',
      tags: ['italy', 'tax', 'fiscal', 'validation', 'check'],
      icon: 'verified',
    },
    {
      id: 'jwt',
      name: 'JWT Decoder',
      description: 'Decode and inspect JSON Web Tokens — header, payload and signature.',
      category: 'Security',
      route: '/tools/jwt',
      tags: ['jwt', 'token', 'auth', 'security', 'decoder'],
      icon: 'key',
      featured: true,
    },
    {
      id: 'one-line',
      name: 'To One Line',
      description: 'Collapse multi-line text to a single line and remove extra spaces.',
      category: 'Text Processing',
      route: '/tools/one-line',
      tags: ['text', 'whitespace', 'one line', 'normalize'],
      icon: 'format_align_justify',
    },
    {
      id: 'space-remover',
      name: 'Space Remover',
      description: 'Strip all whitespace characters from any text.',
      category: 'Text Processing',
      route: '/tools/space-remover',
      tags: ['text', 'whitespace', 'remove', 'trim'],
      icon: 'space_bar',
    },
    {
      id: 'string-length',
      name: 'String Length',
      description: 'Count characters, words, lines and byte size of any text.',
      category: 'Text Processing',
      route: '/tools/string-length',
      tags: ['text', 'count', 'length', 'words', 'lines'],
      icon: 'text_fields',
    },
    {
      id: 'unit-converter',
      name: 'Unit Converter',
      description: 'Convert SI metric units to US customary units — length, mass, volume, temperature, speed.',
      category: 'Conversion',
      route: '/tools/unit-converter',
      tags: ['units', 'metric', 'imperial', 'us', 'conversion'],
      icon: 'straighten',
    },
    {
      id: 'json-formatter',
      name: 'JSON Formatter',
      description: 'Pretty-print, minify and validate JSON documents.',
      category: 'Developer Tools',
      route: '/tools/json-formatter',
      tags: ['json', 'format', 'pretty', 'minify', 'validator'],
      icon: 'data_object',
      featured: true,
    },
    {
      id: 'json-yaml',
      name: 'JSON ↔ YAML',
      description: 'Bidirectional JSON / YAML converter.',
      category: 'Conversion',
      route: '/tools/json-yaml',
      tags: ['json', 'yaml', 'conversion'],
      icon: 'swap_horiz',
    },
    {
      id: 'json-csv',
      name: 'JSON ↔ CSV',
      description: 'Convert between JSON arrays of objects and CSV.',
      category: 'Conversion',
      route: '/tools/json-csv',
      tags: ['json', 'csv', 'conversion', 'spreadsheet'],
      icon: 'table_chart',
    },
    {
      id: 'url-codec',
      name: 'URL Encode / Decode',
      description: 'Percent-encode and decode URLs and query parameters.',
      category: 'Developer Tools',
      route: '/tools/url-codec',
      tags: ['url', 'encode', 'decode', 'percent'],
      icon: 'link',
    },
    {
      id: 'epoch',
      name: 'Epoch / Unix Timestamp',
      description: 'Convert between Unix epoch timestamps and human-readable dates.',
      category: 'Date/Time',
      route: '/tools/epoch',
      tags: ['epoch', 'unix', 'timestamp', 'date', 'time'],
      icon: 'schedule',
    },
    {
      id: 'cron',
      name: 'Cron Expression Builder',
      description: 'Explain and design cron expressions (5 or 6 fields), à la crontab.guru.',
      category: 'Developer Tools',
      route: '/tools/cron',
      tags: ['cron', 'crontab', 'schedule', 'scheduling'],
      icon: 'pending_actions',
    },
    {
      id: 'password-hash',
      name: 'Password Hash',
      description: 'Compute MD5, SHA-1, SHA-256, SHA-384, SHA-512 and bcrypt hashes — all client-side, nothing leaves your browser.',
      category: 'Security',
      route: '/tools/password-hash',
      tags: ['hash', 'password', 'sha', 'md5', 'crypto'],
      icon: 'lock',
    },
    {
      id: 'password-generator',
      name: 'Password Generator',
      description: 'Generate strong passwords using a cryptographically-secure random generator.',
      category: 'Security',
      route: '/tools/password-generator',
      tags: ['password', 'generator', 'random', 'crypto', 'security'],
      icon: 'password',
      featured: true,
    },
    {
      id: 'my-ip',
      name: 'My IP',
      description: 'Discover your public IP address (the only tool that performs a network request).',
      category: 'Developer Tools',
      route: '/tools/my-ip',
      tags: ['ip', 'network', 'public'],
      icon: 'public',
    },
    {
      id: 'cidr-subnet-calculator',
      name: 'CIDR / Subnet Calculator',
      description: 'Analyze CIDR blocks and calculate subnet mask, network, broadcast and usable IPs.',
      category: 'Developer Tools',
      route: '/tools/cidr-subnet-calculator',
      tags: ['cidr', 'subnet', 'ip', 'mask', 'network', 'broadcast', 'ipv4'],
      icon: 'lan',
    },
    {
      id: 'ip-subnet-calculator',
      name: 'IP + Subnet Mask Calculator',
      description: 'Enter an IP and subnet mask or prefix to calculate the network and available IP addresses.',
      category: 'Developer Tools',
      route: '/tools/ip-subnet-calculator',
      tags: ['ip', 'subnet', 'mask', 'prefix', 'network', 'host', 'ipv4'],
      icon: 'settings_ethernet',
    },
    {
      id: 'percentage',
      name: 'Percentage Calculator',
      description: 'Calculate percentages, ratios and percentage changes.',
      category: 'Conversion',
      route: '/tools/percentage',
      tags: ['percentage', 'percent', 'ratio', 'calculation', 'math'],
      icon: 'percent',
    },
    {
      id: 'iva-calculator',
      name: 'Calcolatore IVA',
      description: 'Calcola il prezzo con IVA e senza IVA con aliquote italiane: 4%, 5%, 10%, 22%.',
      category: 'Finance',
      route: '/tools/iva-calculator',
      tags: ['iva', 'vat', 'tassa', 'prezzo', 'italia', 'finanza'],
      icon: 'receipt_long',
    },
    {
      id: 'discount-calculator',
      name: 'Calcolatore Sconto',
      description: 'Calcola il prezzo scontato a partire dal prezzo originale e dalla percentuale di sconto.',
      category: 'Finance',
      route: '/tools/discount-calculator',
      tags: ['sconto', 'discount', 'prezzo', 'percentuale', 'calcolo', 'risparmio'],
      icon: 'sell',
    },
    {
      id: 'uuid-generator',
      name: 'UUID / ULID Generator',
      description: 'Generate cryptographically secure UUID v4 and ULID identifiers.',
      category: 'Developer Tools',
      route: '/tools/uuid-generator',
      tags: ['uuid', 'ulid', 'guid', 'id', 'random', 'generator', 'unique'],
      icon: 'fingerprint',
      featured: true,
    },
    {
      id: 'regex-tester',
      name: 'Regex Tester',
      description: 'Testa espressioni regolari in tempo reale con evidenziazione dei match.',
      category: 'Developer Tools',
      route: '/tools/regex-tester',
      tags: ['regex', 'regexp', 'pattern', 'matching', 'test'],
      icon: 'manage_search',
    },
    {
      id: 'diff-checker',
      name: 'Diff Checker',
      description: 'Confronta due testi riga per riga ed evidenzia le differenze.',
      category: 'Text Processing',
      route: '/tools/diff-checker',
      tags: ['diff', 'compare', 'text', 'difference', 'patch'],
      icon: 'difference',
    },
    {
      id: 'base-converter',
      name: 'Convertitore di Basi',
      description: 'Converti numeri tra binario, ottale, decimale ed esadecimale.',
      category: 'Developer Tools',
      route: '/tools/base-converter',
      tags: ['binary', 'hex', 'octal', 'decimal', 'base', 'conversion', 'number'],
      icon: 'tag',
    },
    {
      id: 'case-converter',
      name: 'Case Converter',
      description: 'Converti testo in camelCase, PascalCase, snake_case, kebab-case e altri formati. Es.: «hello world» → tutti i formati insieme.',
      category: 'Text Processing',
      route: '/tools/case-converter',
      tags: ['case', 'camel', 'pascal', 'snake', 'kebab', 'upper', 'lower', 'text'],
      icon: 'text_format',
    },
    {
      id: 'camel-case',
      name: 'camelCase Converter',
      description: 'Converti testo in camelCase — ideale per nomi di variabili e funzioni. Es.: «hello world» → «helloWorld».',
      category: 'Text Processing',
      route: '/tools/camel-case',
      tags: ['camel', 'case', 'text', 'variable', 'naming'],
      icon: 'text_format',
    },
    {
      id: 'pascal-case',
      name: 'PascalCase Converter',
      description: 'Converti testo in PascalCase — ideale per nomi di classi e componenti. Es.: «hello world» → «HelloWorld».',
      category: 'Text Processing',
      route: '/tools/pascal-case',
      tags: ['pascal', 'case', 'text', 'class', 'naming'],
      icon: 'text_format',
    },
    {
      id: 'snake-case',
      name: 'snake_case Converter',
      description: 'Converti testo in snake_case — ideale per variabili Python e colonne di database. Es.: «hello world» → «hello_world».',
      category: 'Text Processing',
      route: '/tools/snake-case',
      tags: ['snake', 'case', 'text', 'python', 'naming'],
      icon: 'text_format',
    },
    {
      id: 'kebab-case',
      name: 'kebab-case Converter',
      description: 'Converti testo in kebab-case — ideale per classi CSS e slug URL. Es.: «hello world» → «hello-world».',
      category: 'Text Processing',
      route: '/tools/kebab-case',
      tags: ['kebab', 'case', 'text', 'css', 'url', 'naming'],
      icon: 'text_format',
    },
    {
      id: 'constant-case',
      name: 'CONSTANT_CASE Converter',
      description: 'Converti testo in CONSTANT_CASE — ideale per costanti e variabili d\'ambiente. Es.: «hello world» → «HELLO_WORLD».',
      category: 'Text Processing',
      route: '/tools/constant-case',
      tags: ['constant', 'case', 'text', 'env', 'naming'],
      icon: 'text_format',
    },
    {
      id: 'upper-case',
      name: 'UPPER CASE Converter',
      description: 'Converti testo in MAIUSCOLO. Es.: «hello world» → «HELLO WORLD».',
      category: 'Text Processing',
      route: '/tools/upper-case',
      tags: ['upper', 'case', 'text', 'uppercase', 'maiuscolo'],
      icon: 'text_format',
    },
    {
      id: 'lower-case',
      name: 'lower case Converter',
      description: 'Converti testo in minuscolo. Es.: «Hello World» → «hello world».',
      category: 'Text Processing',
      route: '/tools/lower-case',
      tags: ['lower', 'case', 'text', 'lowercase', 'minuscolo'],
      icon: 'text_format',
    },
    {
      id: 'title-case',
      name: 'Title Case Converter',
      description: 'Converti testo in Title Case — la prima lettera di ogni parola in maiuscolo. Es.: «hello world» → «Hello World».',
      category: 'Text Processing',
      route: '/tools/title-case',
      tags: ['title', 'case', 'text', 'capitalize', 'naming'],
      icon: 'text_format',
    },
    {
      id: 'word-counter',
      name: 'Contatore Parole',
      description: 'Conta parole, caratteri, frasi, paragrafi, righe e stima il tempo di lettura.',
      category: 'Text Processing',
      route: '/tools/word-counter',
      tags: ['word', 'count', 'characters', 'reading time', 'text', 'paragraphs'],
      icon: 'spellcheck',
    },
    {
      id: 'slug-generator',
      name: 'Generatore di Slug',
      description: 'Genera URL slug SEO-friendly da un titolo, rimuovendo accenti e caratteri speciali.',
      category: 'Text Processing',
      route: '/tools/slug-generator',
      tags: ['slug', 'url', 'seo', 'text', 'permalink'],
      icon: 'link',
    },
    {
      id: 'age-calculator',
      name: 'Calcolatore di Età',
      description: 'Calcola l\'età esatta in anni, mesi e giorni dalla data di nascita.',
      category: 'Date/Time',
      route: '/tools/age-calculator',
      tags: ['age', 'birthday', 'date', 'birth', 'years', 'calculator'],
      icon: 'cake',
    },
    {
      id: 'html-encoder',
      name: 'HTML Encode / Decode',
      description: 'Codifica e decodifica entità HTML. Converti caratteri speciali in entità HTML e viceversa.',
      category: 'Developer Tools',
      route: '/tools/html-encoder',
      tags: ['html', 'encode', 'decode', 'entities', 'escape', 'unescape', 'web'],
      icon: 'code',
    },
    {
      id: 'color-converter',
      name: 'Convertitore Colori',
      description: 'Converti colori tra HEX, RGB e HSL con anteprima visiva in tempo reale.',
      category: 'Developer Tools',
      route: '/tools/color-converter',
      tags: ['color', 'hex', 'rgb', 'hsl', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'hex-to-rgb',
      name: 'HEX → RGB',
      description: 'Converti un colore HEX nei valori RGB corrispondenti.',
      category: 'Developer Tools',
      route: '/tools/hex-to-rgb',
      tags: ['color', 'hex', 'rgb', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'hex-to-hsl',
      name: 'HEX → HSL',
      description: 'Converti un colore HEX nei valori HSL corrispondenti.',
      category: 'Developer Tools',
      route: '/tools/hex-to-hsl',
      tags: ['color', 'hex', 'hsl', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'rgb-to-hex',
      name: 'RGB → HEX',
      description: 'Converti valori RGB nel codice colore HEX corrispondente.',
      category: 'Developer Tools',
      route: '/tools/rgb-to-hex',
      tags: ['color', 'rgb', 'hex', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'hsl-to-hex',
      name: 'HSL → HEX',
      description: 'Converti valori HSL nel codice colore HEX corrispondente.',
      category: 'Developer Tools',
      route: '/tools/hsl-to-hex',
      tags: ['color', 'hsl', 'hex', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'rgb-to-hsl',
      name: 'RGB → HSL',
      description: 'Converti valori RGB nei valori HSL corrispondenti.',
      category: 'Developer Tools',
      route: '/tools/rgb-to-hsl',
      tags: ['color', 'rgb', 'hsl', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'hsl-to-rgb',
      name: 'HSL → RGB',
      description: 'Converti valori HSL nei valori RGB corrispondenti.',
      category: 'Developer Tools',
      route: '/tools/hsl-to-rgb',
      tags: ['color', 'hsl', 'rgb', 'converter', 'design', 'css'],
      icon: 'palette',
    },
    {
      id: 'color-picker',
      name: 'Color Picker',
      description: 'Scegli un colore visivamente e ottieni i valori HEX, RGB e HSL con un clic. Es.: #3B82F6 → rgb(59, 130, 246) → hsl(217, 91%, 60%).',
      category: 'Developer Tools',
      route: '/tools/color-picker',
      tags: ['color', 'picker', 'hex', 'rgb', 'hsl', 'design', 'css'],
      icon: 'colorize',
    },
    {
      id: 'lorem-ipsum',
      name: 'Generatore Lorem Ipsum',
      description: 'Genera testo Lorem Ipsum per mockup e prototipi. Paragrafi, frasi o parole.',
      category: 'Text Processing',
      route: '/tools/lorem-ipsum',
      tags: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'design'],
      icon: 'article',
    },
    {
      id: 'sql-formatter',
      name: 'Formattatore SQL',
      description: 'Formatta e abbellisce query SQL con indentazione automatica.',
      category: 'Developer Tools',
      route: '/tools/sql-formatter',
      tags: ['sql', 'format', 'query', 'database', 'beautify', 'indent'],
      icon: 'storage',
    },
    {
      id: 'date-diff',
      name: 'Differenza tra Date',
      description: 'Calcola la differenza esatta tra due date in giorni, settimane, mesi e anni.',
      category: 'Date/Time',
      route: '/tools/date-diff',
      tags: ['date', 'difference', 'days', 'months', 'years', 'calculator', 'duration'],
      icon: 'date_range',
    },
    {
      id: 'timezone-converter',
      name: 'Convertitore Fuso Orario',
      description: 'Converti un orario tra i principali fusi orari del mondo.',
      category: 'Date/Time',
      route: '/tools/timezone-converter',
      tags: ['timezone', 'time zone', 'utc', 'convert', 'world clock', 'dst'],
      icon: 'public',
    },
    {
      id: 'partita-iva',
      name: 'Validatore Partita IVA',
      description: 'Verifica la validità di una Partita IVA italiana con controllo del checksum.',
      category: 'Italian Tools',
      route: '/tools/partita-iva',
      tags: ['partita iva', 'piva', 'vat', 'italian', 'validator', 'checksum', 'fiscale'],
      icon: 'receipt',
    },
    {
      id: 'hmac-generator',
      name: 'Generatore HMAC',
      description: 'Genera firme HMAC SHA-256 e SHA-512 con chiave segreta per API e autenticazione.',
      category: 'Security',
      route: '/tools/hmac-generator',
      tags: ['hmac', 'sha256', 'sha512', 'hash', 'signature', 'api', 'crypto', 'security'],
      icon: 'key',
    },
    {
      id: 'random-token',
      name: 'Generatore Token / Secret',
      description: 'Genera token casuali sicuri per API key, JWT secret, password e segreti.',
      category: 'Security',
      route: '/tools/random-token',
      tags: ['token', 'secret', 'random', 'api key', 'jwt', 'password', 'entropy', 'hex', 'base64'],
      icon: 'password',
    },
    {
      id: 'roman-numbers',
      name: 'Numeri Romani',
      description: 'Converti numeri arabi in numeri romani e viceversa. Da I a MMMCMXCIX.',
      category: 'Math',
      route: '/tools/roman-numbers',
      tags: ['roman', 'numerals', 'converter', 'I', 'V', 'X', 'L', 'C', 'D', 'M'],
      icon: 'history_edu',
    },
    {
      id: 'number-words',
      name: 'Numero in Lettere',
      description: 'Converti numeri in parole italiane. Es. 1234 → milleduecentotrentaquattro.',
      category: 'Italian Tools',
      route: '/tools/number-words',
      tags: ['numero', 'lettere', 'parole', 'italiano', 'contratti', 'documenti', 'spell'],
      icon: 'text_fields',
    },
    {
      id: 'jpg-to-webp',
      name: 'JPG → WebP',
      description: 'Converti immagini JPG/JPEG in formato WebP con controllo qualità.',
      category: 'Image Tools',
      route: '/tools/jpg-to-webp',
      tags: ['jpg', 'jpeg', 'webp', 'convert', 'image', 'immagine', 'compress', 'canvas'],
      icon: 'image',
    },
    {
      id: 'png-to-webp',
      name: 'PNG → WebP',
      description: 'Converti immagini PNG in formato WebP con controllo qualità.',
      category: 'Image Tools',
      route: '/tools/png-to-webp',
      tags: ['png', 'webp', 'convert', 'image', 'immagine', 'compress', 'canvas'],
      icon: 'image',
    },
    {
      id: 'webp-converter',
      name: 'WebP → PNG / JPG',
      description: 'Converti immagini WebP in PNG o JPG. Compatibile con tutti i browser.',
      category: 'Image Tools',
      route: '/tools/webp-converter',
      tags: ['webp', 'png', 'jpg', 'convert', 'image', 'immagine', 'canvas'],
      icon: 'swap_horiz',
    },
    {
      id: 'image-resizer',
      name: 'Ridimensiona Immagine',
      description: 'Ridimensiona immagini impostando larghezza e altezza. Mantieni le proporzioni.',
      category: 'Image Tools',
      route: '/tools/image-resizer',
      tags: ['resize', 'ridimensiona', 'image', 'immagine', 'width', 'height', 'scale', 'canvas'],
      icon: 'photo_size_select_large',
    },
    {
      id: 'image-to-base64',
      name: 'Image to Base64',
      description: 'Convert image files to Base64 strings or data URLs and download the result as TXT when needed.',
      category: 'Image Tools',
      route: '/tools/image-to-base64',
      tags: ['image', 'base64', 'data url', 'convert', 'encoder', 'txt', 'browser'],
      icon: 'binary',
    },
    {
      id: 'image-compressor',
      name: 'Comprimi Immagine',
      description: 'Comprimi immagini online con controllo qualità in tempo reale. Vedi la riduzione delle dimensioni.',
      category: 'Image Tools',
      route: '/tools/image-compressor',
      tags: ['compress', 'comprimi', 'quality', 'qualità', 'image', 'immagine', 'optimize', 'canvas'],
      icon: 'compress',
    },
    {
      id: 'image-crop',
      name: 'Ritaglia Immagine',
      description: 'Ritaglia immagini con selettore interattivo. Trascina per selezionare l\'area.',
      category: 'Image Tools',
      route: '/tools/image-crop',
      tags: ['crop', 'ritaglia', 'image', 'immagine', 'cut', 'taglia', 'canvas', 'resize'],
      icon: 'crop',
    },
    {
      id: 'favicon-generator',
      name: 'Favicon Generator',
      description: 'Generate a favicon.ico from any image. Creates a multi-size ICO file (16×16, 32×32, 48×48) in the browser.',
      category: 'Image Tools',
      route: '/tools/favicon-generator',
      tags: ['favicon', 'ico', 'icon', 'image', 'immagine', 'website', 'browser', 'convert', 'canvas'],
      icon: 'tab',
    },
    {
      id: 'tira-il-dado',
      name: 'Tira il Dado',
      description: 'Lancia uno o più dadi virtuali: D4, D6, D8, D10, D12, D20, D100.',
      category: 'Fun',
      route: '/tools/tira-il-dado',
      tags: ['dado', 'dice', 'roll', 'd6', 'd20', 'random', 'gioco', 'game'],
      icon: 'casino',
    },
    {
      id: 'numero-random',
      name: 'Numero Casuale',
      description: 'Estrai uno o più numeri casuali in un intervallo personalizzato.',
      category: 'Fun',
      route: '/tools/numero-random',
      tags: ['numero', 'casuale', 'random', 'intervallo', 'estrai', 'sorteggio'],
      icon: 'shuffle',
    },
    {
      id: 'testa-o-croce',
      name: 'Testa o Croce',
      description: 'Lancia una moneta virtuale: testa o croce. Con storico dei lanci.',
      category: 'Fun',
      route: '/tools/testa-o-croce',
      tags: ['testa', 'croce', 'moneta', 'coin', 'flip', 'random', 'gioco'],
      icon: 'toll',
    },
    {
      id: 'credit-card-validator',
      name: 'Credit Card Validator',
      description: 'Valida numeri di carte con algoritmo Luhn e rilevamento circuito (Visa, Mastercard, Amex, ecc.).',
      category: 'Finance',
      route: '/tools/credit-card-validator',
      tags: ['credit card', 'luhn', 'validator', 'visa', 'mastercard', 'amex', 'payment'],
      icon: 'credit_card',
    },
    {
      id: 'semver-checker',
      name: 'Semver Comparator + Range Checker',
      description: 'Confronta versioni semantiche e verifica se una versione soddisfa un range.',
      category: 'Developer Tools',
      route: '/tools/semver-checker',
      tags: ['semver', 'version', 'range', 'npm', 'compare', 'satisfies'],
      icon: 'rule',
    },
    {
      id: 'qr-generator',
      name: 'Generatore QR Code',
      description: 'Genera QR Code personalizzati da testo o URL con download PNG.',
      category: 'Developer Tools',
      route: '/tools/qr-generator',
      tags: ['qr', 'qrcode', 'generator', 'url', 'text', 'png'],
      icon: 'qr_code_2',
    },
    {
      id: 'barcode-generator',
      name: 'Generatore Barcode',
      description: 'Generatore barcode 1D online nel browser: crea codici CODE128, EAN13, EAN8, UPC, ITF14, MSI e Pharmacode con anteprima immediata e download PNG.',
      category: 'Developer Tools',
      route: '/tools/barcode-generator',
      tags: ['barcode', 'ean13', 'ean8', 'upc', 'code128', 'itf14', 'msi', 'pharmacode', 'generator', 'label', 'png'],
      icon: 'barcode',
    },
    {
      id: 'barcode-reader',
      name: 'Lettore Barcode',
      description: 'Legge barcode da immagini con riconoscimento locale nel browser.',
      category: 'Developer Tools',
      route: '/tools/barcode-reader',
      tags: ['barcode', 'reader', 'scan', 'ean', 'upc', 'code128'],
      icon: 'document_scanner',
    },
    {
      id: 'qrcode-reader',
      name: 'Lettore QR Code',
      description: 'Decodifica QR Code da immagini e copia il contenuto estratto.',
      category: 'Developer Tools',
      route: '/tools/qrcode-reader',
      tags: ['qr', 'qrcode', 'reader', 'scan', 'decode'],
      icon: 'qr_code_scanner',
    },
    {
      id: 'text-inverter',
      name: 'Invertitore di Testo',
      description: 'Inverti testo per caratteri, parole o righe.',
      category: 'Text Processing',
      route: '/tools/text-inverter',
      tags: ['text', 'invert', 'reverse', 'characters', 'words', 'lines'],
      icon: 'swap_horiz',
    },
    {
      id: 'find-replace',
      name: 'Trova e Sostituisci Testo',
      description: 'Trova e sostituisci testo con supporto regex, case sensitive e globale.',
      category: 'Text Processing',
      route: '/tools/find-replace',
      tags: ['find', 'replace', 'text', 'regex', 'search'],
      icon: 'find_replace',
    },
    {
      id: 'image-rotate',
      name: 'Image Rotate',
      description: 'Ruota immagini di qualsiasi angolo con anteprima.',
      category: 'Image Tools',
      route: '/tools/image-rotate',
      tags: ['image', 'rotate', 'photo', 'editor', 'canvas'],
      icon: 'rotate_right',
    },
    {
      id: 'image-flip',
      name: 'Image Flip',
      description: 'Ribalta immagini orizzontalmente e verticalmente.',
      category: 'Image Tools',
      route: '/tools/image-flip',
      tags: ['image', 'flip', 'mirror', 'photo', 'editor'],
      icon: 'flip',
    },
    {
      id: 'image-watermark',
      name: 'Watermark Immagine',
      description: 'Aggiungi watermark testuale su immagini direttamente nel browser.',
      category: 'Image Tools',
      route: '/tools/image-watermark',
      tags: ['image', 'watermark', 'text', 'copyright', 'photo'],
      icon: 'branding_watermark',
    },
    {
      id: 'palette-generator',
      name: 'Palette Generator',
      description: 'Genera palette da un colore base usando input HEX e color picker.',
      category: 'Developer Tools',
      route: '/tools/palette-generator',
      tags: ['palette', 'color', 'generator', 'hex', 'picker', 'design', 'brand'],
      icon: 'palette',
    },
    {
      id: 'palette-from-image',
      name: 'Palette da Immagine',
      description: 'Estrai i colori dominanti da una foto o screenshot.',
      category: 'Image Tools',
      route: '/tools/palette-from-image',
      tags: ['palette', 'image', 'extract', 'dominant colors', 'design', 'brand'],
      icon: 'palette',
    },
    {
      id: 'image-color-picker',
      name: 'Colore da Immagine',
      description: 'Carica un\'immagine, clicca su qualsiasi punto e ottieni il colore HEX, RGB e HSL.',
      category: 'Image Tools',
      route: '/tools/image-color-picker',
      tags: ['image', 'color', 'picker', 'color picker', 'eyedropper', 'hex', 'rgb', 'hsl', 'sample', 'pick color'],
      icon: 'colorize',
    },
    {
      id: 'image-blur',
      name: 'Sfoca Immagine',
      description: 'Applica un effetto blur a un\'immagine con raggio personalizzabile. Download PNG nel browser.',
      category: 'Image Tools',
      route: '/tools/image-blur',
      tags: ['image', 'blur', 'gaussian', 'soften', 'effect', 'photo', 'editor'],
      icon: 'blur_on',
    },
    {
      id: 'image-pixelate',
      name: 'Pixelate Immagine',
      description: 'Applica un effetto pixel-art a un\'immagine con dimensione blocco personalizzabile.',
      category: 'Image Tools',
      route: '/tools/image-pixelate',
      tags: ['image', 'pixelate', 'pixel', 'mosaic', 'effect', 'photo', 'editor', 'pixel-art'],
      icon: 'grid_on',
    },
    {
      id: 'bmi-calculator',
      name: 'Calcolatore BMI',
      description: 'Calcola il tuo Indice di Massa Corporea (BMI) inserendo altezza e peso. Visualizza la categoria e la scala di riferimento.',
      category: 'Health',
      route: '/tools/bmi-calculator',
      tags: ['bmi', 'body mass index', 'peso', 'altezza', 'salute', 'health', 'calculator', 'weight', 'height'],
      icon: 'monitor_weight',
    },
    {
      id: 'gif-maker',
      name: 'GIF Maker',
      description: 'Crea GIF animate da più immagini direttamente nel browser. Imposta la durata dei frame e la dimensione dell\'output.',
      category: 'Image Tools',
      route: '/tools/gif-maker',
      tags: ['gif', 'animated', 'image', 'frames', 'maker', 'create', 'animation', 'gif maker'],
      icon: 'gif',
    },
    {
      id: 'random-wheel',
      name: 'Ruota Fortunata',
      description: 'Ruota della fortuna con elementi personalizzabili. Ideale per decisioni casuali, sorteggi o giochi.',
      category: 'Fun & Games',
      route: '/tools/random-wheel',
      tags: ['random', 'wheel', 'picker', 'spin', 'fortune', 'decision', 'ruota', 'sorteggio', 'casino'],
      icon: 'casino',
    },
    {
      id: 'pomodoro',
      name: 'Pomodoro Timer',
      description: 'Timer Pomodoro online con sessioni di lavoro e pause configurabili. Aumenta la concentrazione e la produttività.',
      category: 'Productivity',
      route: '/tools/pomodoro',
      tags: ['pomodoro', 'timer', 'focus', 'work', 'break', 'productivity', 'produttività', 'concentrazione'],
      icon: 'timer',
    },
    {
      id: 'pdf-merge',
      name: 'Unisci PDF',
      description: 'Unisci più file PDF in un unico documento. Riordina i file prima di combinarli.',
      category: 'PDF Tools',
      route: '/tools/pdf-merge',
      tags: ['pdf', 'merge', 'combine', 'unisci', 'join', 'documents'],
      icon: 'merge',
    },
    {
      id: 'pdf-split',
      name: 'Dividi PDF',
      description: 'Separa ogni pagina di un PDF in un file distinto. Scarica le pagine singolarmente.',
      category: 'PDF Tools',
      route: '/tools/pdf-split',
      tags: ['pdf', 'split', 'dividi', 'pages', 'separate', 'extract'],
      icon: 'call_split',
    },
    {
      id: 'pdf-compress',
      name: 'Comprimi PDF',
      description: 'Ottimizza e riduci le dimensioni di un PDF eliminando dati ridondanti.',
      category: 'PDF Tools',
      route: '/tools/pdf-compress',
      tags: ['pdf', 'compress', 'comprimi', 'optimize', 'reduce', 'size', 'file'],
      icon: 'compress',
    },
    {
      id: 'pdf-rotate',
      name: 'Ruota PDF',
      description: 'Ruota le pagine di un PDF di 90°, 180° o 270°. Applica a tutte le pagine o a una selezione.',
      category: 'PDF Tools',
      route: '/tools/pdf-rotate',
      tags: ['pdf', 'rotate', 'ruota', 'pages', 'orientation', 'landscape', 'portrait'],
      icon: 'rotate_right',
    },
    {
      id: 'pdf-reorder',
      name: 'Riordina Pagine PDF',
      description: 'Cambia l\'ordine delle pagine di un PDF con semplici frecce su/giù.',
      category: 'PDF Tools',
      route: '/tools/pdf-reorder',
      tags: ['pdf', 'reorder', 'riordina', 'pages', 'sort', 'arrange'],
      icon: 'swap_vert',
    },
    {
      id: 'pdf-extract',
      name: 'Estrai Pagine PDF',
      description: 'Estrai un intervallo di pagine da un PDF e salvale in un nuovo documento.',
      category: 'PDF Tools',
      route: '/tools/pdf-extract',
      tags: ['pdf', 'extract', 'estrai', 'pages', 'range', 'select'],
      icon: 'content_cut',
    },
    {
      id: 'pdf-viewer',
      name: 'Visualizza PDF',
      description: 'Apri e visualizza file PDF direttamente nel browser senza installare nulla.',
      category: 'PDF Tools',
      route: '/tools/pdf-viewer',
      tags: ['pdf', 'viewer', 'visualizza', 'view', 'open', 'read', 'browser'],
      icon: 'picture_as_pdf',
    },
    {
      id: 'pdf-to-image',
      name: 'PDF in Immagini',
      description: 'Converti ogni pagina di un PDF in un\'immagine PNG ad alta risoluzione.',
      category: 'PDF Tools',
      route: '/tools/pdf-to-image',
      tags: ['pdf', 'image', 'png', 'convert', 'screenshot', 'render', 'pages'],
      icon: 'image',
    },
    {
      id: 'image-to-pdf',
      name: 'Immagini in PDF',
      description: 'Converti una o più immagini (JPG, PNG) in un PDF. Ogni immagine diventa una pagina.',
      category: 'PDF Tools',
      route: '/tools/image-to-pdf',
      tags: ['image', 'pdf', 'convert', 'jpg', 'png', 'create', 'scan'],
      icon: 'add_photo_alternate',
    },
    {
      id: 'stopwatch',
      name: 'Cronometro',
      description: 'Cronometro online con giri e tempi parziali. Preciso al centesimo di secondo.',
      category: 'Utility',
      route: '/tools/stopwatch',
      tags: ['stopwatch', 'cronometro', 'giri', 'timer', 'lap', 'tempo'],
      icon: 'timer',
    },
    {
      id: 'countdown-timer',
      name: 'Conto alla Rovescia',
      description: 'Timer conto alla rovescia con ore, minuti e secondi. Barra di avanzamento e avviso di scadenza.',
      category: 'Utility',
      route: '/tools/countdown-timer',
      tags: ['countdown', 'conto alla rovescia', 'timer', 'scadenza'],
      icon: 'hourglass_empty',
    },
    {
      id: 'tic-tac-toe',
      name: 'Tris (Tic Tac Toe)',
      description: 'Gioca a Tris contro un amico o sfida il computer con intelligenza artificiale imbattibile.',
      category: 'Games',
      route: '/tools/tic-tac-toe',
      tags: ['tris', 'tic tac toe', 'gioco', 'game', 'cpu', 'minimax', 'divertimento'],
      icon: 'grid_3x3',
    },
    {
      id: 'typing-speed',
      name: 'Test Velocità di Scrittura',
      description: 'Misura le tue parole al minuto (WPM) e accuratezza mentre digiti testi in italiano.',
      category: 'Games',
      route: '/tools/typing-speed',
      tags: ['typing', 'scrittura', 'velocità', 'wpm', 'parole', 'tastiera', 'test'],
      icon: 'keyboard',
    },
    {
      id: 'reaction-time',
      name: 'Test Tempo di Reazione',
      description: 'Misura il tuo tempo di reazione in millisecondi con il test del semaforo o eventi casuali.',
      category: 'Games',
      route: '/tools/reaction-time',
      tags: ['reazione', 'reaction', 'semaforo', 'riflessi', 'tempo', 'test', 'ms'],
      icon: 'bolt',
    },
  ];

  getAll(): ToolCatalogItem[] {
    return [...this.tools];
  }

  getFeatured(): ToolCatalogItem[] {
    return this.tools.filter((t) => t.featured);
  }
}
